name: publish-to-npm
on:
    release:
        types: [created]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: volta-cli/action@v4.0.0
            - name: Install
              run: yarn install --immutable --check-cache
            - name: Build
              run: yarn run build
            - name: Publish
              run: yarn npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPMJS_CLOUDFLIGHT_ADMIN_CI_TOKEN }}
